Belegverarbeitung
rzlsoftware/rzl-online-hilfe pull request #12
Opened 2024-04-04 12:47 UTC by JakobFerdinand

2024-07-15 14:00 UTC, KarinGross93 requested changes
BITTE meine Entdeckungen noch berücksichtigen!

2024-07-15 14:00 UTC, KarinGross93 commented on docs/Belegverarbeitung/Belegverarbeitung im RZL Board/Grundeinstellungen.md
> +**Belegschablonen**
ich würde hier Überschrift ## machen damit rechts ein Verzeichnis kommt

2024-07-15 14:00 UTC, KarinGross93 commented on docs/Belegverarbeitung/Belegverarbeitung im RZL Board/Grundeinstellungen.md
> +**Texterkennung (OCR)**
ich würde hier Überschrift ## machen damit rechts ein Verzeichnis kommt

2024-07-15 14:00 UTC, KarinGross93 commented on docs/Belegverarbeitung/Belegverarbeitung im RZL Board/Grundeinstellungen.md
> +**Stempel**
ich würde hier Überschrift ## machen damit rechts ein Verzeichnis kommt

2024-07-15 14:00 UTC, KarinGross93 commented on docs/Belegverarbeitung/Belegverarbeitung im RZL Board/Grundeinstellungen.md
> +**Grundeinstellungen**
ich würde hier Überschrift ## machen damit rechts ein Verzeichnis kommt

2024-07-15 14:00 UTC, KarinGross93 commented on docs/Belegverarbeitung/Belegverarbeitung im RZL Board/Grundeinstellungen.md
> +Siehe Kurzanleitung *RZL Modul Belegfreigabe* unter *Hilfe /
vielleicht tatsächlichen externen Link hier einfügen -https://rzlsoftware.at/fileadmin/user_upload/PDF_Kurzanleitungen/BELEG/BELEGE_Belegfreigabe.pdf
Bzw. irgendwann werden wir die Kurzanleitung so wie in Fibu Next auch vil direkt im dem Handbuch ergänzen - aber das musst jetzt nicht du machen

2024-07-15 14:00 UTC, KarinGross93 commented on docs/Belegverarbeitung/Belegverarbeitung im RZL Board/Grundeinstellungen.md
> +Siehe Kurzanleitung *RZL Modul Belegfreigabe* unter *Hilfe /
Eigentlich ist im Handbuch das Zusatzmodul Belegfreigabe nicht unter Grundeinstellungen sondern ein eigener Punkt
Magst du bitte auch eine eigene Seite für das Zusatzmodul Belegfreigabe einfügen. Danke

2024-07-15 14:00 UTC, KarinGross93 commented on docs/Belegverarbeitung/Modul Belege am RZL Klientenportal.md
für meinen Geschmack ist hier zu viel auf einer Seite - so dass rechts das Verzeichnis schon zu voll ist.
ich würde es gut finden wenn wir dies noch auf einzelne Seiten aufteilen ( Belege an Steuerberater bzw. in die Zentrale übermitteln; Automatische Belegsynchronisation zur Belegbox am RZL Klientenportal , gebuchte Belege manuell; Übersicht Belege zum Abholen) 
vorteil ist dass man es dann links aufklappen kann

2024-07-15 14:00 UTC, KarinGross93 commented on docs/Belegverarbeitung/Modul Belege am RZL Klientenportal.md
> +Kurzanleitung (Menüpunkt *Hilfe / Kurzanleitungen* direkt im jeweiligen
hier können wir den richtigen Link auch reingeben - zusätzlich

2024-07-15 14:00 UTC, KarinGross93 commented on docs/Belegverarbeitung/Modul Belege am RZL Klientenportal.md
> +Klientenportal *(Hilfe / Handbuch / Klienten-Portal Klient)* Kapitel
hier könnten wir auch den richtigen Link zusätzlich einfügen

2024-07-15 14:00 UTC, KarinGross93 commented on docs/Belegverarbeitung/Modul Belege am RZL Klientenportal.md
> +innerhalb der RZL-Programme im Programmteil *Hilfe / Handbücher /
hier könnte man tatsächlichen Link auch noch zusätzlich hinterlegen

2024-07-15 14:00 UTC, KarinGross93 commented on docs/Belegverarbeitung/Verarbeitung in der RZL FIBU.md
ich würde diese Seite auch aufteilen
Buchen mit digitalen Belegen 
Buchen im EA-Rechner mit Belegverarbeitung
und die anderen 2 als eine separate Seite wäre glaub ich gut

2024-07-15 14:00 UTC, KarinGross93 commented on docs/Belegverarbeitung/Gebuchte Belege aufrufen.md
> +# Belegfreigabe
dieses Kapitel bitte auf eine eigene Seite und Link auf Kurzanleitung hinzufügen

2024-07-22 08:14 UTC, KarinGross93 submitted a review, later dismissed

2024-07-22 09:08 UTC, CorneliaDax approved these changes

2024-07-22 09:08 UTC, merged